### ISSUE TITLE
Discovering data entities in train ticket

### ISSUE THREAD

**Issue by svacina** [cloudhubs/prophet-utils#13]
- create version 0.0.8 of prophet-utils in new branch named 0.0.8-dev
- just quick explenation, the postfix "dev" after version is important, because we are going to develop version 0.0.8 in branch 0.0.8-dev and then we will create 0.0.8 and will close 0.0.8-dev
- modify the library so it can discover both entity annotations in tms and https://github.com/cloudhubs/train-ticket

**Comment by vinbush** [comment]
Implemented in 0.0.8-dev branch
